# Default values for demo1.

replicaCount: 1

# Pod security context
podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Image configurations for multiple repositories
images:
  backend:
    repository: 992382774897.dkr.ecr.us-east-1.amazonaws.com/backend
    pullPolicy: IfNotPresent
    tag: "1"
  frontend:
    repository: 992382774897.dkr.ecr.us-east-1.amazonaws.com/frontend
    pullPolicy: IfNotPresent
    tag: "1"
  socket:
    repository: 992382774897.dkr.ecr.us-east-1.amazonaws.com/socket
    pullPolicy: IfNotPresent
    tag: "1"

# Image pull secrets
imagePullSecrets: []

# Service account settings
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Resources
resources: {}

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: 80 # or whatever your service port is
readinessProbe:
  httpGet:
    path: /
    port: 80 # or whatever your service port is

# Autoscaling settings
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes
volumes: []

# Volume mounts
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

